version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app    
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379    
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./client:/app    
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app    
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        depends_on: 
            - postgres
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '3000:80'
        depends_on: 
            - api
            - client